//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensek.Net.MeterReading.Api.Tests.Unit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ensek.Net.MeterReading.Api.Tests.Unit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountId,MeterReadingDateTime
        ///2344,22/04/2019 09:24
        ///2346,22/04/2019 12:25
        ///2349,22/04/2019 12:25
        ///2356,07/05/2019 09:24
        ///2344,08/05/2019 09:24
        ///6776,09/05/2019 09:24
        ///1235,13/05/2019 09:24
        ///1241,11/04/2019 09:24,X.
        /// </summary>
        internal static string InvalidTestMeterReadingFileContent {
            get {
                return ResourceManager.GetString("InvalidTestMeterReadingFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountId,MeterReadingDateTime,MeterReadValue
        ///2344,22/04/2019 09:24,01002
        ///2346,22/04/2019 12:25,999999
        ///2349,22/04/2019 12:25,VOID
        ///2356,07/05/2019 09:24,00000
        ///2344,08/05/2019 09:24,0X765
        ///6776,09/05/2019 09:24,-06575
        ///1235,13/05/2019 09:24,
        ///1241,11/04/2019 09:24,00436,X.
        /// </summary>
        internal static string TestMeterReadingFileContent {
            get {
                return ResourceManager.GetString("TestMeterReadingFileContent", resourceCulture);
            }
        }
    }
}
