global using System;
global using Xunit;
global using FluentAssertions;
global using Microsoft.Extensions.Options;
global using FakeItEasy;
global using System.Diagnostics.CodeAnalysis;
global using System.Data;
global using Microsoft.Data.Sqlite;
global using Ensek.Net.MeterReading.Shared.Exceptions;